server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # FD Account Service Routes
        - id: fd-account-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/fd-accounts/**
          filters:
            - StripPrefix=0

        # Product Pricing Service Routes
        - id: product-pricing-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0

        # Customer Service Routes
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=0

        # FD Calculator Service Routes
        - id: fd-calculator-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/calculator/**
          filters:
            - StripPrefix=0

        # Login/Auth Service Routes (placeholder - update with actual port when known)
        - id: login-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/login/**, /api/auth/**
          filters:
            - StripPrefix=0

      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      # Default filters for all routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
